// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_BedroomView_screen_init(void)
{
    ui_BedroomView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BedroomView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BedroomView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedroomView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bedroom = lv_img_create(ui_BedroomView);
    lv_img_set_src(ui_Bedroom, &ui_img_bedroom_png);
    lv_obj_set_width(ui_Bedroom, LV_SIZE_CONTENT);   /// 472
    lv_obj_set_height(ui_Bedroom, LV_SIZE_CONTENT);    /// 472
    lv_obj_set_x(ui_Bedroom, 152);
    lv_obj_set_y(ui_Bedroom, -1);
    lv_obj_set_align(ui_Bedroom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Bedroom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Bedroom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BedroomViewTitle = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomViewTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomViewTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomViewTitle, -220);
    lv_obj_set_y(ui_BedroomViewTitle, -180);
    lv_obj_set_align(ui_BedroomViewTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomViewTitle, "Bedroom");
    lv_obj_set_style_text_font(ui_BedroomViewTitle, &ui_font_Heading, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomTempVal = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomTempVal, -360);
    lv_obj_set_y(ui_BedroomTempVal, -80);
    lv_obj_set_align(ui_BedroomTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomTempVal, "0");
    lv_obj_set_style_text_font(ui_BedroomTempVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomTempLabel = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomTempLabel, -279);
    lv_obj_set_y(ui_BedroomTempLabel, -95);
    lv_obj_set_align(ui_BedroomTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomTempLabel, "Temperature");
    lv_obj_set_style_text_font(ui_BedroomTempLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomTempUnits = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomTempUnits, -135);
    lv_obj_set_y(ui_BedroomTempUnits, -95);
    lv_obj_set_align(ui_BedroomTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomTempUnits, "C");
    lv_obj_set_style_text_font(ui_BedroomTempUnits, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomTempGradient = lv_bar_create(ui_BedroomView);
    lv_bar_set_range(ui_BedroomTempGradient, -10, 110);
    lv_obj_set_width(ui_BedroomTempGradient, 199);
    lv_obj_set_height(ui_BedroomTempGradient, 14);
    lv_obj_set_x(ui_BedroomTempGradient, -222);
    lv_obj_set_y(ui_BedroomTempGradient, -75);
    lv_obj_set_align(ui_BedroomTempGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BedroomTempGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedroomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BedroomTempGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BedroomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BedroomTempGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BedroomTempGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_BedroomTempGradient, &ui_img_tempgradientdetailed_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BedroomHumidityVal = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomHumidityVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomHumidityVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomHumidityVal, -360);
    lv_obj_set_y(ui_BedroomHumidityVal, -20);
    lv_obj_set_align(ui_BedroomHumidityVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomHumidityVal, "0");
    lv_obj_set_style_text_font(ui_BedroomHumidityVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomHumidityLabel = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomHumidityLabel, -290);
    lv_obj_set_y(ui_BedroomHumidityLabel, -35);
    lv_obj_set_align(ui_BedroomHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomHumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_BedroomHumidityLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomHumidityGradient = lv_bar_create(ui_BedroomView);
    lv_bar_set_range(ui_BedroomHumidityGradient, -10, 110);
    lv_obj_set_width(ui_BedroomHumidityGradient, 199);
    lv_obj_set_height(ui_BedroomHumidityGradient, 14);
    lv_obj_set_x(ui_BedroomHumidityGradient, -222);
    lv_obj_set_y(ui_BedroomHumidityGradient, -15);
    lv_obj_set_align(ui_BedroomHumidityGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BedroomHumidityGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedroomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BedroomHumidityGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BedroomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BedroomHumidityGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BedroomHumidityGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_BedroomHumidityGradient, &ui_img_humiditygradient_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_BedroomPresenceLabel = lv_label_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomPresenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomPresenceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomPresenceLabel, -285);
    lv_obj_set_y(ui_BedroomPresenceLabel, 45);
    lv_obj_set_align(ui_BedroomPresenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomPresenceLabel, "Presence");
    lv_obj_set_style_text_font(ui_BedroomPresenceLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomPresenceIndicator = lv_obj_create(ui_BedroomView);
    lv_obj_set_width(ui_BedroomPresenceIndicator, 112);
    lv_obj_set_height(ui_BedroomPresenceIndicator, 22);
    lv_obj_set_x(ui_BedroomPresenceIndicator, -179);
    lv_obj_set_y(ui_BedroomPresenceIndicator, 44);
    lv_obj_set_align(ui_BedroomPresenceIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BedroomPresenceIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BedroomPresenceIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BedroomPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BedroomPresenceIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BedroomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_BedroomPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_BedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_BedroomPresenceIndicator, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_BedroomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_BedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_BedroomPresenceIndicator, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_BedroomPresenceIndicator, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Bedroom, ui_event_Bedroom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BedroomView, ui_event_BedroomView, LV_EVENT_ALL, NULL);

}
