// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_KitchenView_screen_init(void)
{
    ui_KitchenView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_KitchenView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KitchenView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KitchenView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Kitchen = lv_img_create(ui_KitchenView);
    lv_img_set_src(ui_Kitchen, &ui_img_kitchen_png);
    lv_obj_set_width(ui_Kitchen, LV_SIZE_CONTENT);   /// 483
    lv_obj_set_height(ui_Kitchen, LV_SIZE_CONTENT);    /// 452
    lv_obj_set_x(ui_Kitchen, 132);
    lv_obj_set_y(ui_Kitchen, -2);
    lv_obj_set_align(ui_Kitchen, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Kitchen, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Kitchen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KitchenViewTitle = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenViewTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenViewTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenViewTitle, -256);
    lv_obj_set_y(ui_KitchenViewTitle, -180);
    lv_obj_set_align(ui_KitchenViewTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenViewTitle, "Kitchen");
    lv_obj_set_style_text_font(ui_KitchenViewTitle, &ui_font_Heading, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenTempGradient = lv_bar_create(ui_KitchenView);
    lv_bar_set_range(ui_KitchenTempGradient, -10, 110);
    lv_obj_set_width(ui_KitchenTempGradient, 199);
    lv_obj_set_height(ui_KitchenTempGradient, 14);
    lv_obj_set_x(ui_KitchenTempGradient, -222);
    lv_obj_set_y(ui_KitchenTempGradient, -75);
    lv_obj_set_align(ui_KitchenTempGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_KitchenTempGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KitchenTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_KitchenTempGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_KitchenTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_KitchenTempGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_KitchenTempGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_KitchenTempGradient, &ui_img_tempgradientdetailed_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_KitchenTempLabel = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenTempLabel, -279);
    lv_obj_set_y(ui_KitchenTempLabel, -95);
    lv_obj_set_align(ui_KitchenTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenTempLabel, "Temperature");
    lv_obj_set_style_text_font(ui_KitchenTempLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenTempVal = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenTempVal, -360);
    lv_obj_set_y(ui_KitchenTempVal, -80);
    lv_obj_set_align(ui_KitchenTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenTempVal, "0");
    lv_obj_set_style_text_font(ui_KitchenTempVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenTempUnits = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenTempUnits, -135);
    lv_obj_set_y(ui_KitchenTempUnits, -95);
    lv_obj_set_align(ui_KitchenTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenTempUnits, "C");
    lv_obj_set_style_text_font(ui_KitchenTempUnits, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenHumidityVal = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenHumidityVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenHumidityVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenHumidityVal, -360);
    lv_obj_set_y(ui_KitchenHumidityVal, -20);
    lv_obj_set_align(ui_KitchenHumidityVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenHumidityVal, "0");
    lv_obj_set_style_text_font(ui_KitchenHumidityVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenHumidityGradient = lv_bar_create(ui_KitchenView);
    lv_bar_set_range(ui_KitchenHumidityGradient, -10, 110);
    lv_obj_set_width(ui_KitchenHumidityGradient, 199);
    lv_obj_set_height(ui_KitchenHumidityGradient, 14);
    lv_obj_set_x(ui_KitchenHumidityGradient, -222);
    lv_obj_set_y(ui_KitchenHumidityGradient, -15);
    lv_obj_set_align(ui_KitchenHumidityGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_KitchenHumidityGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KitchenHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_KitchenHumidityGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_KitchenHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_KitchenHumidityGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_KitchenHumidityGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_KitchenHumidityGradient, &ui_img_humiditygradient_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_KitchenHumidityLabel = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenHumidityLabel, -290);
    lv_obj_set_y(ui_KitchenHumidityLabel, -35);
    lv_obj_set_align(ui_KitchenHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenHumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_KitchenHumidityLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenPresenceLabel = lv_label_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenPresenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenPresenceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenPresenceLabel, -285);
    lv_obj_set_y(ui_KitchenPresenceLabel, 45);
    lv_obj_set_align(ui_KitchenPresenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenPresenceLabel, "Presence");
    lv_obj_set_style_text_font(ui_KitchenPresenceLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenPresenceIndicator = lv_obj_create(ui_KitchenView);
    lv_obj_set_width(ui_KitchenPresenceIndicator, 112);
    lv_obj_set_height(ui_KitchenPresenceIndicator, 22);
    lv_obj_set_x(ui_KitchenPresenceIndicator, -179);
    lv_obj_set_y(ui_KitchenPresenceIndicator, 44);
    lv_obj_set_align(ui_KitchenPresenceIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KitchenPresenceIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KitchenPresenceIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KitchenPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_KitchenPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_KitchenPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_KitchenPresenceIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KitchenPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_KitchenPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_KitchenPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_KitchenPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_KitchenPresenceIndicator, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_KitchenPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_KitchenPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_KitchenPresenceIndicator, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_KitchenPresenceIndicator, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Kitchen, ui_event_Kitchen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_KitchenView, ui_event_KitchenView, LV_EVENT_ALL, NULL);

}
