// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_LaundryRoomView_screen_init(void)
{
    ui_LaundryRoomView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LaundryRoomView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LaundryRoomView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaundryRoomView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoom = lv_img_create(ui_LaundryRoomView);
    lv_img_set_src(ui_LaundryRoom, &ui_img_laundryroom_png);
    lv_obj_set_width(ui_LaundryRoom, LV_SIZE_CONTENT);   /// 454
    lv_obj_set_height(ui_LaundryRoom, LV_SIZE_CONTENT);    /// 465
    lv_obj_set_x(ui_LaundryRoom, 162);
    lv_obj_set_y(ui_LaundryRoom, -4);
    lv_obj_set_align(ui_LaundryRoom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LaundryRoom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LaundryRoom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LaundryRoomViewTitle = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomViewTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomViewTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomViewTitle, -230);
    lv_obj_set_y(ui_LaundryRoomViewTitle, -180);
    lv_obj_set_align(ui_LaundryRoomViewTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomViewTitle, "Laundry");
    lv_obj_set_style_text_font(ui_LaundryRoomViewTitle, &ui_font_Heading, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomTempVal = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomTempVal, -360);
    lv_obj_set_y(ui_LaundryRoomTempVal, -80);
    lv_obj_set_align(ui_LaundryRoomTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomTempVal, "80");
    lv_obj_set_style_text_font(ui_LaundryRoomTempVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomTempLabel = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomTempLabel, -279);
    lv_obj_set_y(ui_LaundryRoomTempLabel, -95);
    lv_obj_set_align(ui_LaundryRoomTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomTempLabel, "Temperature");
    lv_obj_set_style_text_font(ui_LaundryRoomTempLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomTempUnits = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomTempUnits, -135);
    lv_obj_set_y(ui_LaundryRoomTempUnits, -95);
    lv_obj_set_align(ui_LaundryRoomTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomTempUnits, "C");
    lv_obj_set_style_text_font(ui_LaundryRoomTempUnits, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomTempGradient = lv_bar_create(ui_LaundryRoomView);
    lv_bar_set_range(ui_LaundryRoomTempGradient, -10, 110);
    lv_bar_set_value(ui_LaundryRoomTempGradient, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LaundryRoomTempGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LaundryRoomTempGradient, 199);
    lv_obj_set_height(ui_LaundryRoomTempGradient, 14);
    lv_obj_set_x(ui_LaundryRoomTempGradient, -222);
    lv_obj_set_y(ui_LaundryRoomTempGradient, -75);
    lv_obj_set_align(ui_LaundryRoomTempGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LaundryRoomTempGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaundryRoomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LaundryRoomTempGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LaundryRoomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LaundryRoomTempGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LaundryRoomTempGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_LaundryRoomTempGradient, &ui_img_tempgradientdetailed_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LaundryRoomHumidityVal = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomHumidityVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomHumidityVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomHumidityVal, -360);
    lv_obj_set_y(ui_LaundryRoomHumidityVal, -20);
    lv_obj_set_align(ui_LaundryRoomHumidityVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomHumidityVal, "50");
    lv_obj_set_style_text_font(ui_LaundryRoomHumidityVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomHumidityLabel = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomHumidityLabel, -290);
    lv_obj_set_y(ui_LaundryRoomHumidityLabel, -35);
    lv_obj_set_align(ui_LaundryRoomHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomHumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_LaundryRoomHumidityLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomHumidityGradient = lv_bar_create(ui_LaundryRoomView);
    lv_bar_set_range(ui_LaundryRoomHumidityGradient, -10, 110);
    lv_bar_set_value(ui_LaundryRoomHumidityGradient, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LaundryRoomHumidityGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LaundryRoomHumidityGradient, 199);
    lv_obj_set_height(ui_LaundryRoomHumidityGradient, 14);
    lv_obj_set_x(ui_LaundryRoomHumidityGradient, -222);
    lv_obj_set_y(ui_LaundryRoomHumidityGradient, -15);
    lv_obj_set_align(ui_LaundryRoomHumidityGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LaundryRoomHumidityGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaundryRoomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LaundryRoomHumidityGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LaundryRoomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LaundryRoomHumidityGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LaundryRoomHumidityGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_LaundryRoomHumidityGradient, &ui_img_humiditygradient_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LaundryRoomPresenceLabel = lv_label_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomPresenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomPresenceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomPresenceLabel, -285);
    lv_obj_set_y(ui_LaundryRoomPresenceLabel, 45);
    lv_obj_set_align(ui_LaundryRoomPresenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomPresenceLabel, "Presence");
    lv_obj_set_style_text_font(ui_LaundryRoomPresenceLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomPresenceIndicator = lv_obj_create(ui_LaundryRoomView);
    lv_obj_set_width(ui_LaundryRoomPresenceIndicator, 112);
    lv_obj_set_height(ui_LaundryRoomPresenceIndicator, 22);
    lv_obj_set_x(ui_LaundryRoomPresenceIndicator, -179);
    lv_obj_set_y(ui_LaundryRoomPresenceIndicator, 44);
    lv_obj_set_align(ui_LaundryRoomPresenceIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LaundryRoomPresenceIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LaundryRoomPresenceIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaundryRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LaundryRoomPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LaundryRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LaundryRoomPresenceIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LaundryRoomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LaundryRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_LaundryRoomPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_LaundryRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_LaundryRoomPresenceIndicator, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_LaundryRoomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_LaundryRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_LaundryRoomPresenceIndicator, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_LaundryRoomPresenceIndicator, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_LaundryRoom, ui_event_LaundryRoom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LaundryRoomView, ui_event_LaundryRoomView, LV_EVENT_ALL, NULL);

}
