// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_LivingRoomView_screen_init(void)
{
    ui_LivingRoomView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LivingRoomView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LivingRoomView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivingRoomView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Livingroom = lv_img_create(ui_LivingRoomView);
    lv_img_set_src(ui_Livingroom, &ui_img_livingroom_png);
    lv_obj_set_width(ui_Livingroom, LV_SIZE_CONTENT);   /// 453
    lv_obj_set_height(ui_Livingroom, LV_SIZE_CONTENT);    /// 453
    lv_obj_set_x(ui_Livingroom, 151);
    lv_obj_set_y(ui_Livingroom, -2);
    lv_obj_set_align(ui_Livingroom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Livingroom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Livingroom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LivingroomViewTitle = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingroomViewTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomViewTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomViewTitle, -200);
    lv_obj_set_y(ui_LivingroomViewTitle, -180);
    lv_obj_set_align(ui_LivingroomViewTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomViewTitle, "Livingroom");
    lv_obj_set_style_text_font(ui_LivingroomViewTitle, &ui_font_Heading, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomTempVal = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingroomTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomTempVal, -360);
    lv_obj_set_y(ui_LivingroomTempVal, -80);
    lv_obj_set_align(ui_LivingroomTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomTempVal, "80");
    lv_obj_set_style_text_font(ui_LivingroomTempVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomTempLabel = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingroomTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomTempLabel, -279);
    lv_obj_set_y(ui_LivingroomTempLabel, -95);
    lv_obj_set_align(ui_LivingroomTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomTempLabel, "Temperature");
    lv_obj_set_style_text_font(ui_LivingroomTempLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomTempUnits = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingroomTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomTempUnits, -135);
    lv_obj_set_y(ui_LivingroomTempUnits, -95);
    lv_obj_set_align(ui_LivingroomTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomTempUnits, "C");
    lv_obj_set_style_text_font(ui_LivingroomTempUnits, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomTempGradient = lv_bar_create(ui_LivingRoomView);
    lv_bar_set_range(ui_LivingroomTempGradient, -10, 110);
    lv_bar_set_value(ui_LivingroomTempGradient, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LivingroomTempGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LivingroomTempGradient, 199);
    lv_obj_set_height(ui_LivingroomTempGradient, 14);
    lv_obj_set_x(ui_LivingroomTempGradient, -222);
    lv_obj_set_y(ui_LivingroomTempGradient, -75);
    lv_obj_set_align(ui_LivingroomTempGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LivingroomTempGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivingroomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LivingroomTempGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LivingroomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LivingroomTempGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LivingroomTempGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_LivingroomTempGradient, &ui_img_tempgradientdetailed_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LivingroomHumidityVal = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingroomHumidityVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomHumidityVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomHumidityVal, -360);
    lv_obj_set_y(ui_LivingroomHumidityVal, -20);
    lv_obj_set_align(ui_LivingroomHumidityVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomHumidityVal, "50");
    lv_obj_set_style_text_font(ui_LivingroomHumidityVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomHumidityLabel = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingroomHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomHumidityLabel, -290);
    lv_obj_set_y(ui_LivingroomHumidityLabel, -35);
    lv_obj_set_align(ui_LivingroomHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomHumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_LivingroomHumidityLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomHumidityGradient = lv_bar_create(ui_LivingRoomView);
    lv_bar_set_range(ui_LivingroomHumidityGradient, -10, 110);
    lv_bar_set_value(ui_LivingroomHumidityGradient, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_LivingroomHumidityGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_LivingroomHumidityGradient, 199);
    lv_obj_set_height(ui_LivingroomHumidityGradient, 14);
    lv_obj_set_x(ui_LivingroomHumidityGradient, -222);
    lv_obj_set_y(ui_LivingroomHumidityGradient, -15);
    lv_obj_set_align(ui_LivingroomHumidityGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LivingroomHumidityGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivingroomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LivingroomHumidityGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LivingroomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_LivingroomHumidityGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_LivingroomHumidityGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_LivingroomHumidityGradient, &ui_img_humiditygradient_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LivingRoomPresenceLabel = lv_label_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingRoomPresenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingRoomPresenceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingRoomPresenceLabel, -285);
    lv_obj_set_y(ui_LivingRoomPresenceLabel, 45);
    lv_obj_set_align(ui_LivingRoomPresenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingRoomPresenceLabel, "Presence");
    lv_obj_set_style_text_font(ui_LivingRoomPresenceLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingRoomPresenceIndicator = lv_obj_create(ui_LivingRoomView);
    lv_obj_set_width(ui_LivingRoomPresenceIndicator, 112);
    lv_obj_set_height(ui_LivingRoomPresenceIndicator, 22);
    lv_obj_set_x(ui_LivingRoomPresenceIndicator, -179);
    lv_obj_set_y(ui_LivingRoomPresenceIndicator, 44);
    lv_obj_set_align(ui_LivingRoomPresenceIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LivingRoomPresenceIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LivingRoomPresenceIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivingRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LivingRoomPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LivingRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LivingRoomPresenceIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LivingRoomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LivingRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_LivingRoomPresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_LivingRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_LivingRoomPresenceIndicator, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_LivingRoomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_LivingRoomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_LivingRoomPresenceIndicator, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_LivingRoomPresenceIndicator, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Livingroom, ui_event_Livingroom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LivingRoomView, ui_event_LivingRoomView, LV_EVENT_ALL, NULL);

}
