// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_MasterBedroomView_screen_init(void)
{
    ui_MasterBedroomView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MasterBedroomView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MasterBedroomView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterBedroomView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroom = lv_img_create(ui_MasterBedroomView);
    lv_img_set_src(ui_MasterBedroom, &ui_img_masterbedroom_png);
    lv_obj_set_width(ui_MasterBedroom, LV_SIZE_CONTENT);   /// 500
    lv_obj_set_height(ui_MasterBedroom, LV_SIZE_CONTENT);    /// 500
    lv_obj_set_x(ui_MasterBedroom, 155);
    lv_obj_set_y(ui_MasterBedroom, -4);
    lv_obj_set_align(ui_MasterBedroom, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MasterBedroom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MasterBedroom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MasterBedroomViewTitle = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomViewTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomViewTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomViewTitle, -220);
    lv_obj_set_y(ui_MasterBedroomViewTitle, -180);
    lv_obj_set_align(ui_MasterBedroomViewTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomViewTitle, "Bedroom");
    lv_obj_set_style_text_font(ui_MasterBedroomViewTitle, &ui_font_Heading, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomTempVal = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomTempVal, -360);
    lv_obj_set_y(ui_MasterBedroomTempVal, -80);
    lv_obj_set_align(ui_MasterBedroomTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomTempVal, "80");
    lv_obj_set_style_text_font(ui_MasterBedroomTempVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomTempLabel = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomTempLabel, -279);
    lv_obj_set_y(ui_MasterBedroomTempLabel, -95);
    lv_obj_set_align(ui_MasterBedroomTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomTempLabel, "Temperature");
    lv_obj_set_style_text_font(ui_MasterBedroomTempLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomTempUnits = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomTempUnits, -135);
    lv_obj_set_y(ui_MasterBedroomTempUnits, -95);
    lv_obj_set_align(ui_MasterBedroomTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomTempUnits, "C");
    lv_obj_set_style_text_font(ui_MasterBedroomTempUnits, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomTempGradient = lv_bar_create(ui_MasterBedroomView);
    lv_bar_set_range(ui_MasterBedroomTempGradient, -10, 110);
    lv_bar_set_value(ui_MasterBedroomTempGradient, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MasterBedroomTempGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MasterBedroomTempGradient, 199);
    lv_obj_set_height(ui_MasterBedroomTempGradient, 14);
    lv_obj_set_x(ui_MasterBedroomTempGradient, -222);
    lv_obj_set_y(ui_MasterBedroomTempGradient, -75);
    lv_obj_set_align(ui_MasterBedroomTempGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MasterBedroomTempGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterBedroomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MasterBedroomTempGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MasterBedroomTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MasterBedroomTempGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MasterBedroomTempGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_MasterBedroomTempGradient, &ui_img_tempgradientdetailed_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MasterBedroomHumidityVal = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomHumidityVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomHumidityVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomHumidityVal, -359);
    lv_obj_set_y(ui_MasterBedroomHumidityVal, -20);
    lv_obj_set_align(ui_MasterBedroomHumidityVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomHumidityVal, "50");
    lv_obj_set_style_text_font(ui_MasterBedroomHumidityVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomHumidityLabel = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomHumidityLabel, -290);
    lv_obj_set_y(ui_MasterBedroomHumidityLabel, -35);
    lv_obj_set_align(ui_MasterBedroomHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomHumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_MasterBedroomHumidityLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomHumidityGradient = lv_bar_create(ui_MasterBedroomView);
    lv_bar_set_range(ui_MasterBedroomHumidityGradient, -10, 110);
    lv_bar_set_value(ui_MasterBedroomHumidityGradient, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_MasterBedroomHumidityGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_MasterBedroomHumidityGradient, 199);
    lv_obj_set_height(ui_MasterBedroomHumidityGradient, 14);
    lv_obj_set_x(ui_MasterBedroomHumidityGradient, -222);
    lv_obj_set_y(ui_MasterBedroomHumidityGradient, -15);
    lv_obj_set_align(ui_MasterBedroomHumidityGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_MasterBedroomHumidityGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterBedroomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MasterBedroomHumidityGradient, lv_color_hex(0x2F3233),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MasterBedroomHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_MasterBedroomHumidityGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_MasterBedroomHumidityGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_MasterBedroomHumidityGradient, &ui_img_humiditygradient_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MasterBedroomPresenceLabel = lv_label_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomPresenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomPresenceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomPresenceLabel, -285);
    lv_obj_set_y(ui_MasterBedroomPresenceLabel, 45);
    lv_obj_set_align(ui_MasterBedroomPresenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomPresenceLabel, "Presence");
    lv_obj_set_style_text_font(ui_MasterBedroomPresenceLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomPresenceIndicator = lv_obj_create(ui_MasterBedroomView);
    lv_obj_set_width(ui_MasterBedroomPresenceIndicator, 112);
    lv_obj_set_height(ui_MasterBedroomPresenceIndicator, 22);
    lv_obj_set_x(ui_MasterBedroomPresenceIndicator, -179);
    lv_obj_set_y(ui_MasterBedroomPresenceIndicator, 44);
    lv_obj_set_align(ui_MasterBedroomPresenceIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MasterBedroomPresenceIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MasterBedroomPresenceIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterBedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MasterBedroomPresenceIndicator, lv_color_hex(0x293031),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MasterBedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MasterBedroomPresenceIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MasterBedroomPresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_MasterBedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_MasterBedroomPresenceIndicator, lv_color_hex(0x293031),
                                  LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_MasterBedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_MasterBedroomPresenceIndicator, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_MasterBedroomPresenceIndicator, lv_color_hex(0xFFF700),
                                  LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_MasterBedroomPresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_MasterBedroomPresenceIndicator, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_MasterBedroomPresenceIndicator, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_MasterBedroom, ui_event_MasterBedroom, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MasterBedroomView, ui_event_MasterBedroomView, LV_EVENT_ALL, NULL);

}
