// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_OfficeView_screen_init(void)
{
    ui_OfficeView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OfficeView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OfficeView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfficeView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Office = lv_img_create(ui_OfficeView);
    lv_img_set_src(ui_Office, &ui_img_office_png);
    lv_obj_set_width(ui_Office, LV_SIZE_CONTENT);   /// 470
    lv_obj_set_height(ui_Office, LV_SIZE_CONTENT);    /// 473
    lv_obj_set_x(ui_Office, 157);
    lv_obj_set_y(ui_Office, 1);
    lv_obj_set_align(ui_Office, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Office, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Office, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OfficeViewTitle = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficeViewTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeViewTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeViewTitle, -260);
    lv_obj_set_y(ui_OfficeViewTitle, -180);
    lv_obj_set_align(ui_OfficeViewTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeViewTitle, "Office");
    lv_obj_set_style_text_font(ui_OfficeViewTitle, &ui_font_Heading, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeTempVal = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficeTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeTempVal, -360);
    lv_obj_set_y(ui_OfficeTempVal, -80);
    lv_obj_set_align(ui_OfficeTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeTempVal, "80");
    lv_obj_set_style_text_font(ui_OfficeTempVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeTempLabel = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficeTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeTempLabel, -279);
    lv_obj_set_y(ui_OfficeTempLabel, -95);
    lv_obj_set_align(ui_OfficeTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeTempLabel, "Temperature");
    lv_obj_set_style_text_font(ui_OfficeTempLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeTempUnits = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficeTempUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeTempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeTempUnits, -135);
    lv_obj_set_y(ui_OfficeTempUnits, -95);
    lv_obj_set_align(ui_OfficeTempUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeTempUnits, "C");
    lv_obj_set_style_text_font(ui_OfficeTempUnits, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeTempGradient = lv_bar_create(ui_OfficeView);
    lv_bar_set_range(ui_OfficeTempGradient, -10, 110);
    lv_bar_set_value(ui_OfficeTempGradient, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_OfficeTempGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_OfficeTempGradient, 199);
    lv_obj_set_height(ui_OfficeTempGradient, 14);
    lv_obj_set_x(ui_OfficeTempGradient, -222);
    lv_obj_set_y(ui_OfficeTempGradient, -75);
    lv_obj_set_align(ui_OfficeTempGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_OfficeTempGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfficeTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_OfficeTempGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_OfficeTempGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_OfficeTempGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_OfficeTempGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_OfficeTempGradient, &ui_img_tempgradientdetailed_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_OfficeHumidityVal = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficeHumidityVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeHumidityVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeHumidityVal, -360);
    lv_obj_set_y(ui_OfficeHumidityVal, -20);
    lv_obj_set_align(ui_OfficeHumidityVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeHumidityVal, "50");
    lv_obj_set_style_text_font(ui_OfficeHumidityVal, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeHumidityLabel = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficeHumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeHumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeHumidityLabel, -290);
    lv_obj_set_y(ui_OfficeHumidityLabel, -35);
    lv_obj_set_align(ui_OfficeHumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeHumidityLabel, "Humidity");
    lv_obj_set_style_text_font(ui_OfficeHumidityLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeHumidityGradient = lv_bar_create(ui_OfficeView);
    lv_bar_set_range(ui_OfficeHumidityGradient, -10, 110);
    lv_bar_set_value(ui_OfficeHumidityGradient, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_OfficeHumidityGradient, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_OfficeHumidityGradient, 199);
    lv_obj_set_height(ui_OfficeHumidityGradient, 14);
    lv_obj_set_x(ui_OfficeHumidityGradient, -222);
    lv_obj_set_y(ui_OfficeHumidityGradient, -15);
    lv_obj_set_align(ui_OfficeHumidityGradient, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_OfficeHumidityGradient, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfficeHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_OfficeHumidityGradient, lv_color_hex(0x2F3233), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_OfficeHumidityGradient, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_OfficeHumidityGradient, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_OfficeHumidityGradient, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_img_src(ui_OfficeHumidityGradient, &ui_img_humiditygradient_png,
                                LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_OfficePresenceLabel = lv_label_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficePresenceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficePresenceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficePresenceLabel, -285);
    lv_obj_set_y(ui_OfficePresenceLabel, 45);
    lv_obj_set_align(ui_OfficePresenceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficePresenceLabel, "Presence");
    lv_obj_set_style_text_font(ui_OfficePresenceLabel, &ui_font_SmallThin, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficePresenceIndicator = lv_obj_create(ui_OfficeView);
    lv_obj_set_width(ui_OfficePresenceIndicator, 112);
    lv_obj_set_height(ui_OfficePresenceIndicator, 22);
    lv_obj_set_x(ui_OfficePresenceIndicator, -179);
    lv_obj_set_y(ui_OfficePresenceIndicator, 44);
    lv_obj_set_align(ui_OfficePresenceIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OfficePresenceIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OfficePresenceIndicator, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfficePresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OfficePresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OfficePresenceIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OfficePresenceIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OfficePresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_OfficePresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(ui_OfficePresenceIndicator, lv_color_hex(0x293031), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_OfficePresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_OfficePresenceIndicator, 1, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_color(ui_OfficePresenceIndicator, lv_color_hex(0xFFF700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_opa(ui_OfficePresenceIndicator, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(ui_OfficePresenceIndicator, 20, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_spread(ui_OfficePresenceIndicator, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_Office, ui_event_Office, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OfficeView, ui_event_OfficeView, LV_EVENT_ALL, NULL);

}
