// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_RoomsView_screen_init(void)
{
    ui_RoomsView = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_RoomsView, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RoomsView, lv_color_hex(0x313839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RoomsView, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KitchenIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_KitchenIcon, 200);
    lv_obj_set_height(ui_KitchenIcon, 200);
    lv_obj_set_x(ui_KitchenIcon, -200);
    lv_obj_set_y(ui_KitchenIcon, -100);
    lv_obj_set_align(ui_KitchenIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KitchenIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_KitchenIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KitchenIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KitchenIcon, &ui_img_kitchenicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_KitchenIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_KitchenIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_KitchenIcon, &ui_img_kitchenicon_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_KitchenIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LivingRoomIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_LivingRoomIcon, 200);
    lv_obj_set_height(ui_LivingRoomIcon, 200);
    lv_obj_set_x(ui_LivingRoomIcon, 0);
    lv_obj_set_y(ui_LivingRoomIcon, -145);
    lv_obj_set_align(ui_LivingRoomIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LivingRoomIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LivingRoomIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LivingRoomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LivingRoomIcon, &ui_img_livingroomicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LivingRoomIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LivingRoomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LivingRoomIcon, &ui_img_livingroomicon_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_LivingRoomIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MasterBedroomIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_MasterBedroomIcon, 200);
    lv_obj_set_height(ui_MasterBedroomIcon, 200);
    lv_obj_set_x(ui_MasterBedroomIcon, 200);
    lv_obj_set_y(ui_MasterBedroomIcon, -100);
    lv_obj_set_align(ui_MasterBedroomIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MasterBedroomIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MasterBedroomIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MasterBedroomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MasterBedroomIcon, &ui_img_masterbedroomicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MasterBedroomIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MasterBedroomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_MasterBedroomIcon, &ui_img_masterbedroomicon_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_MasterBedroomIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LaundryRoomIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_LaundryRoomIcon, 200);
    lv_obj_set_height(ui_LaundryRoomIcon, 200);
    lv_obj_set_x(ui_LaundryRoomIcon, 0);
    lv_obj_set_y(ui_LaundryRoomIcon, 145);
    lv_obj_set_align(ui_LaundryRoomIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LaundryRoomIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LaundryRoomIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaundryRoomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LaundryRoomIcon, &ui_img_laundryroomicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LaundryRoomIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LaundryRoomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_LaundryRoomIcon, &ui_img_laundryroomicon_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_LaundryRoomIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BedRoomIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_BedRoomIcon, 200);
    lv_obj_set_height(ui_BedRoomIcon, 200);
    lv_obj_set_x(ui_BedRoomIcon, -200);
    lv_obj_set_y(ui_BedRoomIcon, 100);
    lv_obj_set_align(ui_BedRoomIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BedRoomIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BedRoomIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BedRoomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BedRoomIcon, &ui_img_bedroomicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BedRoomIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BedRoomIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BedRoomIcon, &ui_img_bedroomicon_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_BedRoomIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_OfficeIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_OfficeIcon, 200);
    lv_obj_set_height(ui_OfficeIcon, 200);
    lv_obj_set_x(ui_OfficeIcon, 200);
    lv_obj_set_y(ui_OfficeIcon, 100);
    lv_obj_set_align(ui_OfficeIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_OfficeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OfficeIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfficeIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_OfficeIcon, &ui_img_officeicon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OfficeIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OfficeIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_OfficeIcon, &ui_img_officeicon_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_OfficeIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_HouseIcon = lv_obj_create(ui_RoomsView);
    lv_obj_set_width(ui_HouseIcon, 90);
    lv_obj_set_height(ui_HouseIcon, 90);
    lv_obj_set_align(ui_HouseIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HouseIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HouseIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HouseIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HouseIcon, &ui_img_tinyhouse_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HouseIcon, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HouseIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HouseIcon, &ui_img_tinyhouse_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_HouseIcon, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_KitchenLabel = lv_label_create(ui_RoomsView);
    lv_obj_set_width(ui_KitchenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KitchenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KitchenLabel, -253);
    lv_obj_set_y(ui_KitchenLabel, -15);
    lv_obj_set_align(ui_KitchenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KitchenLabel, "Kitchen");
    lv_obj_set_style_text_font(ui_KitchenLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LivingroomLabel = lv_label_create(ui_RoomsView);
    lv_obj_set_width(ui_LivingroomLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LivingroomLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LivingroomLabel, 80);
    lv_obj_set_y(ui_LivingroomLabel, -227);
    lv_obj_set_align(ui_LivingroomLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LivingroomLabel, "Livingroom");
    lv_obj_set_style_text_font(ui_LivingroomLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterBedroomLabel = lv_label_create(ui_RoomsView);
    lv_obj_set_width(ui_MasterBedroomLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterBedroomLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterBedroomLabel, 281);
    lv_obj_set_y(ui_MasterBedroomLabel, -10);
    lv_obj_set_align(ui_MasterBedroomLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MasterBedroomLabel, "Master Bedroom");
    lv_obj_set_style_text_font(ui_MasterBedroomLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LaundryRoomLabel = lv_label_create(ui_RoomsView);
    lv_obj_set_width(ui_LaundryRoomLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LaundryRoomLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LaundryRoomLabel, -100);
    lv_obj_set_y(ui_LaundryRoomLabel, 229);
    lv_obj_set_align(ui_LaundryRoomLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LaundryRoomLabel, "Laundry Room");
    lv_obj_set_style_text_font(ui_LaundryRoomLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BedroomLabel = lv_label_create(ui_RoomsView);
    lv_obj_set_width(ui_BedroomLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BedroomLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BedroomLabel, -256);
    lv_obj_set_y(ui_BedroomLabel, 188);
    lv_obj_set_align(ui_BedroomLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BedroomLabel, "Bedroom");
    lv_obj_set_style_text_font(ui_BedroomLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfficeLabel = lv_label_create(ui_RoomsView);
    lv_obj_set_width(ui_OfficeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfficeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfficeLabel, 249);
    lv_obj_set_y(ui_OfficeLabel, 192);
    lv_obj_set_align(ui_OfficeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfficeLabel, "Office");
    lv_obj_set_style_text_font(ui_OfficeLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_KitchenIcon, ui_event_KitchenIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LivingRoomIcon, ui_event_LivingRoomIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MasterBedroomIcon, ui_event_MasterBedroomIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LaundryRoomIcon, ui_event_LaundryRoomIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BedRoomIcon, ui_event_BedRoomIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OfficeIcon, ui_event_OfficeIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HouseIcon, ui_event_HouseIcon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RoomsView, ui_event_RoomsView, LV_EVENT_ALL, NULL);

}
