// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsTitleLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_SettingsTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsTitleLabel, -295);
    lv_obj_set_y(ui_SettingsTitleLabel, -202);
    lv_obj_set_align(ui_SettingsTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsTitleLabel, "Settings");
    lv_obj_set_style_text_color(ui_SettingsTitleLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SettingsTitleLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SettingsTitleLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsTitleLabel, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelButton = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_CancelButton, 120);
    lv_obj_set_height(ui_CancelButton, 35);
    lv_obj_set_x(ui_CancelButton, -100);
    lv_obj_set_y(ui_CancelButton, 210);
    lv_obj_set_align(ui_CancelButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CancelButton, "Cancel");
    lv_obj_add_flag(ui_CancelButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_CancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_CancelButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_CancelButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CancelButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CancelButton, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_CancelButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_CancelButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CancelButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CancelButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CancelButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CancelButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_CancelButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_CancelButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_CancelButton, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_CancelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_CancelButton, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SaveButton = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_SaveButton, 120);
    lv_obj_set_height(ui_SaveButton, 35);
    lv_obj_set_x(ui_SaveButton, 100);
    lv_obj_set_y(ui_SaveButton, 210);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveButton, "Save");
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_SaveButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SaveButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SaveButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SaveButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveButton, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0x069804), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SaveButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SaveButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SaveButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SaveButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SaveButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SaveButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SaveButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_SaveButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_text_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0x0DFF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SaveButton, 100, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_color(ui_SaveButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_SaveButton, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SettingsSavedLabel = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_SettingsSavedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsSavedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsSavedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsSavedLabel, "Settings Saved");
    lv_obj_set_style_text_color(ui_SettingsSavedLabel, lv_color_hex(0x758E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsSavedLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsSavedLabel, &ui_font_SubTitle, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLayout = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_SettingsLayout, 360);
    lv_obj_set_height(ui_SettingsLayout, 360);
    lv_obj_set_x(ui_SettingsLayout, -200);
    lv_obj_set_y(ui_SettingsLayout, 5);
    lv_obj_set_align(ui_SettingsLayout, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsLayout, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_SettingsLayout, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingsLayout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsLayout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsLayout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SettingsLayout, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsLayout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingsLayout, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsLayout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsLayout, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsLayout, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLabel = lv_label_create(ui_SettingsLayout);
    lv_obj_set_width(ui_SSIDLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDLabel, 40);
    lv_obj_set_y(ui_SSIDLabel, -1);
    lv_obj_set_align(ui_SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLabel, "SSID:");
    lv_obj_set_style_text_color(ui_SSIDLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSIDLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSIDLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDInput = lv_textarea_create(ui_SettingsLayout);
    lv_obj_set_width(ui_SSIDInput, 346);
    lv_obj_set_height(ui_SSIDInput, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_align(ui_SSIDInput, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_SSIDInput, 32);
    lv_textarea_set_placeholder_text(ui_SSIDInput, "SSID");
    lv_textarea_set_one_line(ui_SSIDInput, true);
    lv_obj_set_style_text_color(ui_SSIDInput, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSIDInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SSIDInput, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SSIDInput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SSIDInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_PasswordLabel = lv_label_create(ui_SettingsLayout);
    lv_obj_set_width(ui_PasswordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PasswordLabel, 40);
    lv_obj_set_y(ui_PasswordLabel, -1);
    lv_obj_set_align(ui_PasswordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PasswordLabel, "Password:");
    lv_obj_set_style_text_color(ui_PasswordLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PasswordLabel, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordInput = lv_textarea_create(ui_SettingsLayout);
    lv_obj_set_width(ui_PasswordInput, 346);
    lv_obj_set_height(ui_PasswordInput, LV_SIZE_CONTENT);    /// 44
    lv_obj_set_align(ui_PasswordInput, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PasswordInput, 32);
    lv_textarea_set_placeholder_text(ui_PasswordInput, "Password");
    lv_textarea_set_one_line(ui_PasswordInput, true);
    lv_obj_set_style_text_color(ui_PasswordInput, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PasswordInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PasswordInput, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PasswordInput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PasswordInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_TempUnit = lv_label_create(ui_SettingsLayout);
    lv_obj_set_width(ui_TempUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempUnit, 40);
    lv_obj_set_y(ui_TempUnit, -1);
    lv_obj_set_align(ui_TempUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempUnit, "Temperature Units");
    lv_obj_set_style_text_color(ui_TempUnit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempUnit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempUnit, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Celsius = lv_label_create(ui_SettingsLayout);
    lv_obj_set_width(ui_Celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Celsius, 40);
    lv_obj_set_y(ui_Celsius, -1);
    lv_obj_set_align(ui_Celsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Celsius, "F");
    lv_obj_add_flag(ui_Celsius, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_set_style_text_color(ui_Celsius, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Celsius, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Celsius, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_SettingsLayout);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);


    ui_Farenheit = lv_label_create(ui_SettingsLayout);
    lv_obj_set_width(ui_Farenheit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Farenheit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Farenheit, 40);
    lv_obj_set_y(ui_Farenheit, -1);
    lv_obj_set_align(ui_Farenheit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Farenheit, "C");
    lv_obj_set_style_text_color(ui_Farenheit, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Farenheit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Farenheit, &ui_font_Regular, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_CancelButton, ui_event_CancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
