// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void cancel_settings_change(lv_event_t * e);
void save_settings(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
