// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "ui.h"

void cancel_settings_change(lv_event_t * e)
{
	// Your code here
}

void save_settings(lv_event_t * e)
{
	// Your code here
}
