// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: home_monitoring

#include "ui.h"
extern void set_is_celsius(lv_event_t * e);

void cancel_settings_change(lv_event_t * e)
{
	// Your code here
}

void save_settings(lv_event_t * e)
{
	// Your code here
}

void kitchen_temp_unit_change(lv_event_t * e)
{
	// Your code here
}

void temp_unit_change(lv_event_t * e)
{
set_is_celsius(e);
}
